### PR TITLE
Change/Update

### PR DESCRIPTION
**Pull request by Makhuta**
- default valut of name in config flow (from "Sonarr" to "")
- splitted the data parsing for better readidibility
- moved and changed 'default' from parse_data to const for better config
- added dynamic name/id based on if is prrovided name in config flow
- modified README.md according the new config
- added instalation steps into info.md (same as in README.md to be dispalyed in HACS)

### CODE REVIEW

**Comment by Makhuta** [comment]
Here are the naming type "empty default (with testing)" I mentioned [here](https://github.com/custom-components/sensor.sonarr_upcoming_media/pull/35#issuecomment-2057818792)
Hope it is to your liking 😁

**Comment by mkanet** [comment]
@Makhuta great work!  Thanks again for adding this great new enhancement.  You even updated the readme!

**Comment by mkanet** [comment]
@Makhuta I just want to say that this was an AWESOME enhancement! I'm hoping that you will be motivated to also do the same for Radarr Upcoming Media and possibly Plex Recently Added.

**Comment by Makhuta** [comment]
I am planning to do that when I got some time to spare 😄

**Pull request merged**
