### PR TITLE
Add "unmonitored=true" API parapmeter

### PR DESCRIPTION
**Pull request by vampywiz17**
~~Add unmonitored=true parameter to API call. It is a hard coded change, it would be good that is able to make configurable via HA. But it exceeds my programming knowledge.~~

**Edit:** I add a new option, that this change is changeable on HA. I tested it and work with my system, but it need other check.

### CODE REVIEW

**Review by mkanet — COMMENTED** [review]
@vampywiz17 Have you tested this well with Sonarr V4 (non-beta)?

**Comment by mkanet** [comment]
I'm unsure how to even test this or what this change even does.  Please let me know how to test this.  After I confirm it works, I would be happy to merge this pull request.

**Comment by vampywiz17** [comment]
@mkanet 

Hello there,

I dont use this . But i test it and inform you.

**Comment by mkanet** [comment]
Thanks.  I dont use it either.  I'm not comfortable merging this unless you're certain it works correctly as intended without causing other issues.

**Pull request closed without merging**
