### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Makhuta**
- Rewriten to work with config flow
- Added support for multiple instances
- Added name parameter which is used for instance name and id (the unique id is generated from apikey)

### CODE REVIEW

**Comment by mkanet** [comment]
Wow @Makhuta thank you!!  What a nice surprise!  I just tried it, it installed just fine without any issues.  I'll go ahead with merging it soon (by tomorrow).  Any chance you have plans to do the same for some of the other UMC-compatible integrations?

**Comment by Makhuta** [comment]
Yeah sure I will try my best, maybe I will try to make the Sonarr/Radarr ect. in different file so it will be easier to navigate in.

**Comment by Makhuta** [comment]
And probably it would be good to update the README according to current setup, I kinda forgot about it 😅

**Comment by mkanet** [comment]
@Makhuta I just merged it.  One thing I just noticed.  For people that only have a single instance of Sonarr (which is relatively common), The sensor name will default to:   `sensor.sonarr_sonarr_upcoming_media` instead of just `sensor.sonarr_upcoming_media`; even when the `Name` field is left blank.  This might cause some confusion for users who already have their card code defined from previous versions wondering why their card no longer displays after upgrading.

I am currently updating the readme.  If you think we should keep it as-is, I'll change the readme to explain how the `Name` field will affect the sensor name; even when left blank.  I personally don't mind either way since I was able to figure it out.

**Comment by Makhuta** [comment]
If I now remember correctly the name is based on the provided name (obviously), the default value is "Sonarr" which is most likely used when the provided name is entry.
I could make slight change in schematic and in getting/using the name in name/id

**Comment by Makhuta** [comment]
Which you like better @mkanet
- different default (only):
  - name: <code>Default Sonarr Upcomming Media</code>
  - id: <code>sensor.default_sonarr_upcoming_media</code>
- empty default (with testing):
  - if empty:
    - name: <code>Sonarr Upcomming Media</code>
    - id: <code>sensor.sonarr_upcoming_media</code>
  - if filled:
    - name: <code>[PROVIDED NAME] Sonarr Upcomming Media</code>
    - id: <code>sensor.[privided name]_sonarr_upcoming_media</code>

**Comment by mkanet** [comment]
@Makhuta I think `empty default (with testing):
if empty:
name: Sonarr Upcomming Media
id: sensor.sonarr_upcoming_media
if filled:
name: [PROVIDED NAME] Sonarr Upcomming Media
id: sensor.[privided name]_sonarr_upcoming_media` would be best.  It would avoid having to change existing card code for people with a single instance.  It would also allow users to change their configuration to support more than one instance.  Thanks so much!!

**Pull request merged**
